"""Shared Pydantic models for OneData-enabled Domino pieces."""

from __future__ import annotations

from typing import Optional

from pydantic import BaseModel, Field

try:
    from common.onedata_defaults import (
        DEFAULT_ONEDATA_TOKEN,
        DEFAULT_ONEZONE_HOST,
        DEFAULT_OUTPUT_DIR,
    )
except ModuleNotFoundError:
    from pieces.common.onedata_defaults import (
        DEFAULT_ONEDATA_TOKEN,
        DEFAULT_ONEZONE_HOST,
        DEFAULT_OUTPUT_DIR,
    )


class OneDataSecretsModel(BaseModel):
    """OneData credentials — defaults are in ``onedata_defaults.py`` (Domino secrets optional)."""

    onedata_onezone_host: Optional[str] = Field(
        default=DEFAULT_ONEZONE_HOST,
        description="Onedata Onezone host, e.g. data.spice-platform.eu",
    )
    onedata_token: Optional[str] = Field(
        default=DEFAULT_ONEDATA_TOKEN,
        description="Onedata access token (default in code; Domino secrets optional)",
    )
    onedata_output_dir: Optional[str] = Field(
        default=DEFAULT_OUTPUT_DIR,
        description="OneData base dir for run outputs, e.g. onedata:///FilipsSpace/sustainable_model/outputs",
    )


class RunIdInputMixin(BaseModel):
    """Propagated from entry pieces so each run writes to its own output subfolder."""

    run_id: str = Field(
        default="",
        description="Workflow run id (generated by FetchEnergyDataPiece / UserInputPiece when using OneData)",
    )
