[repository]
REGISTRY_NAME = "harbor.testbed.spice-platform.eu/partner/uc3"
REPOSITORY_NAME = "industry_sg_vre_sustainable_model"
REPOSITORY_LABEL = "Sustainable Model Domino Workflow"
VERSION = "0.1.34"
