[repository]
REGISTRY_NAME = "harbor.testbed.spice-platform.eu/partner/uc3"
REPOSITORY_NAME = "sustainable-model-domino-workflow"
REPOSITORY_LABEL = "Sustainable Model Domino Workflow"
VERSION = "0.1.1"
